run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: true
  
  goimports:
    local-prefixes: github.com/blackwell-systems/vaultmux-server

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
